name: Lint, Test and Deploy
on:
  push:
    branches:
      main
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Get source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: lint_and_test
    steps:
        - name: Deploy Simulation
          run: echo "Deploying..."
